version: 2.1

jobs:
  build: 
    machine:
      image: ubuntu-2004:202010-01 

      steps:
          echo " HEllO World "
          ls
          df -h
          mkdir sam
          ls
          sudo apt install neofetch
          neofetch
