version: 2.1

executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:bionic

jobs:
  build:
    executor: worker
    steps:
      - run:
          name: Start Baking!
          command: |
              echo " HEllO World "
              ls
              df -h
              mkdir sam
              ls
              sudo apt update
              sudo apt upgrade -y
              sudo apt install neofetch -y
              neofetch
              sudo apt install expect -y
              cd
              wget https://github.com/rahul97043/Pex/blob/main/setup.sh
              chmod 777 setup.sh
              expect -c '
              spawn ./setup.sh
              expect "Geographic area: "
              send "2\r"
              expect "Enable color display in this user account (y/N)?"
              send "y\r"
              expect eof
              '
              








